# Generated by Django 5.1.6 on 2025-02-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='name',
            field=models.CharField(default='JohnDoe', max_length=255),
            preserve_default=False,
        ),
    ]
