# Generated by Django 5.1.6 on 2025-02-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_store', '0002_baseuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
